<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Sachin-Sharma" ignored="1" name="Default test(failed)" tests="1" failures="1" timestamp="03 Mar 2023 11:59:14 GMT" time="0.094" errors="0">
  <testcase name="test1" time="0.021" classname="com.qa.retryconcept.TestNgRetryDemo">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.qa.retryconcept.TestNgRetryDemo.test1(TestNgRetryDemo.java:9)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.0" classname="com.qa.retryconcept.TestNgRetryDemo">
    <ignored/>
  </testcase> <!-- test2 -->
</testsuite> <!-- Default test(failed) -->
