<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Sachin-Sharma" ignored="0" name="Default test(failed)(failed)(failed)" tests="3" failures="3" timestamp="25 Feb 2022 11:10:31 GMT" time="20.184" errors="0">
  <testcase name="screenShotTest2" time="0.017" classname="com.qa.screenshotfailedtest.ScreenshotTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.qa.screenshotfailedtest.ScreenshotTest.screenShotTest2(ScreenshotTest.java:29)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- screenShotTest2 -->
  <testcase name="screenShotTest1" time="0.003" classname="com.qa.screenshotfailedtest.ScreenshotTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.qa.screenshotfailedtest.ScreenshotTest.screenShotTest1(ScreenshotTest.java:25)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- screenShotTest1 -->
  <testcase name="screenShotTest3" time="0.001" classname="com.qa.screenshotfailedtest.ScreenshotTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.qa.screenshotfailedtest.ScreenshotTest.screenShotTest3(ScreenshotTest.java:33)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- screenShotTest3 -->
</testsuite> <!-- Default test(failed)(failed)(failed) -->
