<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Sachin-Sharma" failures="1" tests="5" name="testng_retry" time="0.111" errors="0" timestamp="20 Sep 2023 06:10:32 GMT">
  <testcase classname="com.qa.retryconcept.TestNgRetryDemo2" name="test1" time="0.016">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="com.qa.retryconcept.TestNgRetryDemo2" name="test1" time="0.004">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="com.qa.retryconcept.TestNgRetryDemo2" name="test1" time="0.003">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="com.qa.retryconcept.TestNgRetryDemo2" name="test1" time="0.002">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.qa.retryconcept.TestNgRetryDemo2.test1(TestNgRetryDemo2.java:12)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="com.qa.retryconcept.TestNgRetryDemo2" name="test2" time="0.014"/>
</testsuite> <!-- testng_retry -->
